### ISSUE TITLE
How get server headers for a request?

### ISSUE THREAD

**Issue by campusboy87** [codenix-sv/coingecko-api#1]
Hi. Thank you for the library! Tell me, how can I get server headers for a request?

```
https://api.coingecko.com/api/v3/exchanges?per_page=10
```

![image](https://user-images.githubusercontent.com/20075333/83743617-a34e1d00-a663-11ea-8d90-df3abb55c79e.png)

Based on this data, I would be able to figure out whether to make more requests and when to stop.

Am I correct in assuming that the library doesn't offer these features right now?

**Comment by codenix-sv** [comment]
Hi. Thank you for your feedback!
Yes, you are right, the library doesn't offer these features right now.
I'll try to implement this features as soon as possible.

**Comment by codenix-sv** [comment]
Hi!
You can get last response (`ResponseInterface::class`) uses `getLastResponse` method:

```php
use Codenixsv\CoinGeckoApi\CoinGeckoClient;

$client = new CoinGeckoClient();
$data = $client->derivatives()->getExchanges();
$response = $client->getLastResponse();
$headers = $response->getHeaders();
```
