### ISSUE TITLE
Guzzle 7

### ISSUE THREAD

**Issue by Paulsky** [codenix-sv/coingecko-api#4]
Hello,

I would like to try this package, but I need Guzzle to be minimum at 7. Do you have any plans to update Guzzle?

**Comment by codenix-sv** [comment]
Hello!
All packages will be updated in the next major version.

**Comment by Paulsky** [comment]
Thank you @codenix-sv, do you have an ETA for that?

**Comment by codenix-sv** [comment]
@Paulsky Sorry, but I don't know (( maybe you can create fork and use it in your project?

**Comment by Paulsky** [comment]
Alright, thank you!
